### PR TITLE
Fix a bug I found when there are more than one group (at same nesting level) under a non null prefix path

### PR DESCRIPTION
**Pull request by jvverde**
Just add two variables and change two lines.

My Problem was:
 
router.group('/v1', (router) => {
  router.group('/auth', ...)
  router.group('/user', ...)
})

routes under /user lost v1 prefix. I expected /v1/user/info and I got /user/info

Best regards

### CODE REVIEW

**Comment by ukayani** [comment]
Thanks for the fix @jvverde. Would you mind adding a test case for this issue?

**Comment by ukayani** [comment]
Curious why we couldn't just add this to our router.spec ? is it because the file is too large as it is?

**Comment by jvverde** [comment]
> Thanks for the fix @jvverde. Would you mind adding a test case for this issue?

I am not used to pull request to others code, so it was my ignorance how to proceed. But I can do that.

**Comment by ukayani** [comment]
Thanks!

**Pull request merged**
